name: Ruff

on: [push]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Ruff
        uses: astral-sh/ruff-action@v2
        with:
          args: check

      - name: Run Ruff Format
        uses: astral-sh/ruff-action@v2
        with:
          args: format --check
